### PR TITLE
Reappropriate logo: for Cayden

### PR DESCRIPTION
**Pull request by cindybro**

### CODE REVIEW

**Comment by cindybro** [comment]
Wuh ohs....this is how it looks on About page right now....

​

On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com wrote:

> Merged #9 https://github.com/18mr/vote/pull/9.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#event-175920116.

## 

CYNTHIA BROTHERS

_CIVIC ENGAGEMENT FELLOW_
347.708.2296
cynthia@18millionrising.org

18MR.org http://www.18mr.org/   |   Facebook
https://www.facebook.com/18MillionRising.org   |   Twitter
https://twitter.com/18millionrising   |   Tumblr http://18mr.tumblr.com/

https://www.facebook.com/18MillionRising
http://twitter.com/18millionrising http://18millionrising.org/

**Comment by catachresis** [comment]
i fixed it!

On Wed, Oct 8, 2014 at 11:31 AM, cindybro notifications@github.com wrote:

> Wuh ohs....this is how it looks on About page right now....
> 
> ​
> 
> On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com wrote:
> 
> > Merged #9 https://github.com/18mr/vote/pull/9.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#event-175920116.
> 
> ## 
> 
> CYNTHIA BROTHERS
> 
> _CIVIC ENGAGEMENT FELLOW_
> 347.708.2296
> cynthia@18millionrising.org
> 
> 18MR.org http://www.18mr.org/ | Facebook
> https://www.facebook.com/18MillionRising.org | Twitter
> https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> 
> https://www.facebook.com/18MillionRising
> http://twitter.com/18millionrising http://18millionrising.org/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58404540.

## 

Cayden Mak

tel: 248/229.9005
bodywithout.org

**Comment by cindybro** [comment]
yay! thank you!! and did i do something wrong, so i can do it right for
next time?

On Wed, Oct 8, 2014 at 11:59 AM, cayden notifications@github.com wrote:

> i fixed it!
> 
> On Wed, Oct 8, 2014 at 11:31 AM, cindybro notifications@github.com
> wrote:
> 
> > Wuh ohs....this is how it looks on About page right now....
> > 
> > ​
> > 
> > On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com
> > wrote:
> > 
> > > Merged #9 https://github.com/18mr/vote/pull/9.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/18mr/vote/pull/9#event-175920116.
> > 
> > ## 
> > 
> > CYNTHIA BROTHERS
> > 
> > _CIVIC ENGAGEMENT FELLOW_
> > 347.708.2296
> > cynthia@18millionrising.org
> > 
> > 18MR.org http://www.18mr.org/ | Facebook
> > https://www.facebook.com/18MillionRising.org | Twitter
> > https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> > 
> > https://www.facebook.com/18MillionRising
> > http://twitter.com/18millionrising http://18millionrising.org/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#issuecomment-58404540.
> 
> ## 
> 
> Cayden Mak
> 
> tel: 248/229.9005
> bodywithout.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58408956.

## 

CYNTHIA BROTHERS

_CIVIC ENGAGEMENT FELLOW_
347.708.2296
cynthia@18millionrising.org

18MR.org http://www.18mr.org/   |   Facebook
https://www.facebook.com/18MillionRising.org   |   Twitter
https://twitter.com/18millionrising   |   Tumblr http://18mr.tumblr.com/

https://www.facebook.com/18MillionRising
http://twitter.com/18millionrising http://18millionrising.org/

**Comment by catachresis** [comment]
looks like the problem was line breaks? take a look at this diff:
https://github.com/18mr/vote/commit/bee3a215ca4e11b5c60a5bcb295bbe3b49dda9ef

On Wed, Oct 8, 2014 at 12:10 PM, cindybro notifications@github.com wrote:

> yay! thank you!! and did i do something wrong, so i can do it right for
> next time?
> 
> On Wed, Oct 8, 2014 at 11:59 AM, cayden notifications@github.com wrote:
> 
> > i fixed it!
> > 
> > On Wed, Oct 8, 2014 at 11:31 AM, cindybro notifications@github.com
> > wrote:
> > 
> > > Wuh ohs....this is how it looks on About page right now....
> > > 
> > > ​
> > > 
> > > On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com
> > > wrote:
> > > 
> > > > Merged #9 https://github.com/18mr/vote/pull/9.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/18mr/vote/pull/9#event-175920116.
> > > 
> > > ## 
> > > 
> > > CYNTHIA BROTHERS
> > > 
> > > _CIVIC ENGAGEMENT FELLOW_
> > > 347.708.2296
> > > cynthia@18millionrising.org
> > > 
> > > 18MR.org http://www.18mr.org/ | Facebook
> > > https://www.facebook.com/18MillionRising.org | Twitter
> > > https://twitter.com/18millionrising | Tumblr <
> > > http://18mr.tumblr.com/>
> > > 
> > > https://www.facebook.com/18MillionRising
> > > http://twitter.com/18millionrising http://18millionrising.org/
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/18mr/vote/pull/9#issuecomment-58404540.
> > 
> > ## 
> > 
> > Cayden Mak
> > 
> > tel: 248/229.9005
> > bodywithout.org
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#issuecomment-58408956.
> 
> ## 
> 
> CYNTHIA BROTHERS
> 
> _CIVIC ENGAGEMENT FELLOW_
> 347.708.2296
> cynthia@18millionrising.org
> 
> 18MR.org http://www.18mr.org/ | Facebook
> https://www.facebook.com/18MillionRising.org | Twitter
> https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> 
> https://www.facebook.com/18MillionRising
> http://twitter.com/18millionrising http://18millionrising.org/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58410555.

## 

Cayden Mak

tel: 248/229.9005
bodywithout.org

**Comment by cindybro** [comment]
Will it help if I add the logo in the comment box instead of directly
editing into the main index box?

And I was using "####" in markdown to make the Reappropriate heading
smaller.....as well as "##" to make a line break between the logos...

On Wed, Oct 8, 2014 at 12:39 PM, cayden notifications@github.com wrote:

> looks like the problem was line breaks? take a look at this diff:
> 
> https://github.com/18mr/vote/commit/bee3a215ca4e11b5c60a5bcb295bbe3b49dda9ef
> 
> On Wed, Oct 8, 2014 at 12:10 PM, cindybro notifications@github.com
> wrote:
> 
> > yay! thank you!! and did i do something wrong, so i can do it right for
> > next time?
> > 
> > On Wed, Oct 8, 2014 at 11:59 AM, cayden notifications@github.com
> > wrote:
> > 
> > > i fixed it!
> > > 
> > > On Wed, Oct 8, 2014 at 11:31 AM, cindybro notifications@github.com
> > > wrote:
> > > 
> > > > Wuh ohs....this is how it looks on About page right now....
> > > > 
> > > > ​
> > > > 
> > > > On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com
> > > > wrote:
> > > > 
> > > > > Merged #9 https://github.com/18mr/vote/pull/9.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/18mr/vote/pull/9#event-175920116.
> > > > 
> > > > ## 
> > > > 
> > > > CYNTHIA BROTHERS
> > > > 
> > > > _CIVIC ENGAGEMENT FELLOW_
> > > > 347.708.2296
> > > > cynthia@18millionrising.org
> > > > 
> > > > 18MR.org http://www.18mr.org/ | Facebook
> > > > https://www.facebook.com/18MillionRising.org | Twitter
> > > > https://twitter.com/18millionrising | Tumblr <
> > > > http://18mr.tumblr.com/>
> > > > 
> > > > https://www.facebook.com/18MillionRising
> > > > http://twitter.com/18millionrising http://18millionrising.org/
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/18mr/vote/pull/9#issuecomment-58404540.
> > > 
> > > ## 
> > > 
> > > Cayden Mak
> > > 
> > > tel: 248/229.9005
> > > bodywithout.org
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/18mr/vote/pull/9#issuecomment-58408956.
> > 
> > ## 
> > 
> > CYNTHIA BROTHERS
> > 
> > _CIVIC ENGAGEMENT FELLOW_
> > 347.708.2296
> > cynthia@18millionrising.org
> > 
> > 18MR.org http://www.18mr.org/ | Facebook
> > https://www.facebook.com/18MillionRising.org | Twitter
> > https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> > 
> > https://www.facebook.com/18MillionRising
> > http://twitter.com/18millionrising http://18millionrising.org/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#issuecomment-58410555.
> 
> ## 
> 
> Cayden Mak
> 
> tel: 248/229.9005
> bodywithout.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58414722.

## 

CYNTHIA BROTHERS

_CIVIC ENGAGEMENT FELLOW_
347.708.2296
cynthia@18millionrising.org

18MR.org http://www.18mr.org/   |   Facebook
https://www.facebook.com/18MillionRising.org   |   Twitter
https://twitter.com/18millionrising   |   Tumblr http://18mr.tumblr.com/

https://www.facebook.com/18MillionRising
http://twitter.com/18millionrising http://18millionrising.org/

**Comment by catachresis** [comment]
Not sure what you mean by that, but the main thing I did was to remove
hashmarks before the image insertion and deleted a space between the alt
text [] and the image url (). Removed hashmarks from before "Reappropriate"
because we don't have a style for h4.

On Wed, Oct 8, 2014 at 12:48 PM, cindybro notifications@github.com wrote:

> Will it help if I add the logo in the comment box instead of directly
> editing into the main index box?
> 
> And I was using "####" in markdown to make the Reappropriate heading
> smaller.....as well as "##" to make a line break between the logos...
> 
> On Wed, Oct 8, 2014 at 12:39 PM, cayden notifications@github.com wrote:
> 
> > looks like the problem was line breaks? take a look at this diff:
> > 
> > https://github.com/18mr/vote/commit/bee3a215ca4e11b5c60a5bcb295bbe3b49dda9ef
> > 
> > On Wed, Oct 8, 2014 at 12:10 PM, cindybro notifications@github.com
> > wrote:
> > 
> > > yay! thank you!! and did i do something wrong, so i can do it right
> > > for
> > > next time?
> > > 
> > > On Wed, Oct 8, 2014 at 11:59 AM, cayden notifications@github.com
> > > wrote:
> > > 
> > > > i fixed it!
> > > > 
> > > > On Wed, Oct 8, 2014 at 11:31 AM, cindybro notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > Wuh ohs....this is how it looks on About page right now....
> > > > > 
> > > > > ​
> > > > > 
> > > > > On Wed, Oct 8, 2014 at 11:15 AM, cayden notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > > Merged #9 https://github.com/18mr/vote/pull/9.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/18mr/vote/pull/9#event-175920116.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > CYNTHIA BROTHERS
> > > > > 
> > > > > _CIVIC ENGAGEMENT FELLOW_
> > > > > 347.708.2296
> > > > > cynthia@18millionrising.org
> > > > > 
> > > > > 18MR.org http://www.18mr.org/ | Facebook
> > > > > https://www.facebook.com/18MillionRising.org | Twitter
> > > > > https://twitter.com/18millionrising | Tumblr <
> > > > > http://18mr.tumblr.com/>
> > > > > 
> > > > > https://www.facebook.com/18MillionRising
> > > > > http://twitter.com/18millionrising http://18millionrising.org/
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/18mr/vote/pull/9#issuecomment-58404540.
> > > > 
> > > > ## 
> > > > 
> > > > Cayden Mak
> > > > 
> > > > tel: 248/229.9005
> > > > bodywithout.org
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/18mr/vote/pull/9#issuecomment-58408956.
> > > 
> > > ## 
> > > 
> > > CYNTHIA BROTHERS
> > > 
> > > _CIVIC ENGAGEMENT FELLOW_
> > > 347.708.2296
> > > cynthia@18millionrising.org
> > > 
> > > 18MR.org http://www.18mr.org/ | Facebook
> > > https://www.facebook.com/18MillionRising.org | Twitter
> > > https://twitter.com/18millionrising | Tumblr <
> > > http://18mr.tumblr.com/>
> > > 
> > > https://www.facebook.com/18MillionRising
> > > http://twitter.com/18millionrising http://18millionrising.org/
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/18mr/vote/pull/9#issuecomment-58410555.
> > 
> > ## 
> > 
> > Cayden Mak
> > 
> > tel: 248/229.9005
> > bodywithout.org
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#issuecomment-58414722.
> 
> ## 
> 
> CYNTHIA BROTHERS
> 
> _CIVIC ENGAGEMENT FELLOW_
> 347.708.2296
> cynthia@18millionrising.org
> 
> 18MR.org http://www.18mr.org/ | Facebook
> https://www.facebook.com/18MillionRising.org | Twitter
> https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> 
> https://www.facebook.com/18MillionRising
> http://twitter.com/18millionrising http://18millionrising.org/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58416078.

## 

Cayden Mak

tel: 248/229.9005
bodywithout.org

**Comment by cindybro** [comment]
Ah, ok. Thanks!!

C

On Wed, Oct 8, 2014 at 1:18 PM, cayden notifications@github.com wrote:

> Not sure what you mean by that, but the main thing I did was to remove
> hashmarks before the image insertion and deleted a space between the alt
> text [] and the image url (). Removed hashmarks from before
> "Reappropriate"
> because we don't have a style for h4.
> 
> On Wed, Oct 8, 2014 at 12:48 PM, cindybro notifications@github.com
> wrote:
> 
> > Will it help if I add the logo in the comment box instead of directly
> > editing into the main index box?
> > 
> > And I was using "####" in markdown to make the Reappropriate heading
> > smaller.....as well as "##" to make a line break between the logos...
> > 
> > On Wed, Oct 8, 2014 at 12:39 PM, cayden notifications@github.com
> > wrote:
> > 
> > > looks like the problem was line breaks? take a look at this diff:
> > 
> > https://github.com/18mr/vote/commit/bee3a215ca4e11b5c60a5bcb295bbe3b49dda9ef
> > 
> > > On Wed, Oct 8, 2014 at 12:10 PM, cindybro notifications@github.com
> > > wrote:
> > > 
> > > > yay! thank you!! and did i do something wrong, so i can do it right
> > > > for
> > > > next time?
> > > > 
> > > > On Wed, Oct 8, 2014 at 11:59 AM, cayden notifications@github.com
> > > > wrote:
> > > > 
> > > > > i fixed it!
> > > > > 
> > > > > On Wed, Oct 8, 2014 at 11:31 AM, cindybro <
> > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > Wuh ohs....this is how it looks on About page right now....
> > > > > > 
> > > > > > ​
> > > > > > 
> > > > > > On Wed, Oct 8, 2014 at 11:15 AM, cayden <
> > > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > > Merged #9 https://github.com/18mr/vote/pull/9.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > https://github.com/18mr/vote/pull/9#event-175920116.
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > CYNTHIA BROTHERS
> > > > > > 
> > > > > > _CIVIC ENGAGEMENT FELLOW_
> > > > > > 347.708.2296
> > > > > > cynthia@18millionrising.org
> > > > > > 
> > > > > > 18MR.org http://www.18mr.org/ | Facebook
> > > > > > https://www.facebook.com/18MillionRising.org | Twitter
> > > > > > https://twitter.com/18millionrising | Tumblr <
> > > > > > http://18mr.tumblr.com/>
> > > > > > 
> > > > > > https://www.facebook.com/18MillionRising
> > > > > > http://twitter.com/18millionrising <
> > > > > > http://18millionrising.org/>
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/18mr/vote/pull/9#issuecomment-58404540.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Cayden Mak
> > > > > 
> > > > > tel: 248/229.9005
> > > > > bodywithout.org
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/18mr/vote/pull/9#issuecomment-58408956.
> > > > 
> > > > ## 
> > > > 
> > > > CYNTHIA BROTHERS
> > > > 
> > > > _CIVIC ENGAGEMENT FELLOW_
> > > > 347.708.2296
> > > > cynthia@18millionrising.org
> > > > 
> > > > 18MR.org http://www.18mr.org/ | Facebook
> > > > https://www.facebook.com/18MillionRising.org | Twitter
> > > > https://twitter.com/18millionrising | Tumblr <
> > > > http://18mr.tumblr.com/>
> > > > 
> > > > https://www.facebook.com/18MillionRising
> > > > http://twitter.com/18millionrising http://18millionrising.org/
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/18mr/vote/pull/9#issuecomment-58410555.
> > > 
> > > ## 
> > > 
> > > Cayden Mak
> > > 
> > > tel: 248/229.9005
> > > bodywithout.org
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/18mr/vote/pull/9#issuecomment-58414722.
> > 
> > ## 
> > 
> > CYNTHIA BROTHERS
> > 
> > _CIVIC ENGAGEMENT FELLOW_
> > 347.708.2296
> > cynthia@18millionrising.org
> > 
> > 18MR.org http://www.18mr.org/ | Facebook
> > https://www.facebook.com/18MillionRising.org | Twitter
> > https://twitter.com/18millionrising | Tumblr http://18mr.tumblr.com/
> > 
> > https://www.facebook.com/18MillionRising
> > http://twitter.com/18millionrising http://18millionrising.org/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/18mr/vote/pull/9#issuecomment-58416078.
> 
> ## 
> 
> Cayden Mak
> 
> tel: 248/229.9005
> bodywithout.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18mr/vote/pull/9#issuecomment-58420325.

## 

CYNTHIA BROTHERS

_CIVIC ENGAGEMENT FELLOW_
347.708.2296
cynthia@18millionrising.org

18MR.org http://www.18mr.org/   |   Facebook
https://www.facebook.com/18MillionRising.org   |   Twitter
https://twitter.com/18millionrising   |   Tumblr http://18mr.tumblr.com/

https://www.facebook.com/18MillionRising
http://twitter.com/18millionrising http://18millionrising.org/

**Pull request merged**
